# Generated by Django 6.1.1 on 2026-09-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('sin_categoria', 'Sin categoría'), ('consulta_tecnica', 'Consulta técnica'), ('compra', 'Compra')], default='sin_categoria', max_length=20)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='chat.conversacion')),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resúmenes',
            },
        ),
    ]
