# Generated by Django 6.1.1 on 2026-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
