# Generated by Django 6.1.1 on 2026-09-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('intencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencion_analisis', to='entrenamiento.intencion')),
                ('mensaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_analisis', to='chat.mensaje')),
            ],
            options={
                'verbose_name': 'Analisis de Mensaje',
                'verbose_name_plural': 'Analisis de Mensajes',
            },
        ),
        migrations.CreateModel(
            name='EntidadDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_detectado', models.TextField()),
                ('inicio', models.PositiveSmallIntegerField()),
                ('fin', models.PositiveSmallIntegerField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_entidad', to='core.analisis')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiqueta_entidad', to='entrenamiento.etiquetaentidad')),
            ],
            options={
                'verbose_name': 'Entidad Detectada',
                'verbose_name_plural': 'Entidades Detectadas',
            },
        ),
    ]
