# Generated by Django 6.1.1 on 2026-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analisis de Mensaje',
                'verbose_name_plural': 'Analisis de Mensajes',
            },
        ),
        migrations.CreateModel(
            name='EntidadDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_detectado', models.TextField()),
            ],
            options={
                'verbose_name': 'Entidad Detectada',
                'verbose_name_plural': 'Entidades Detectadas',
            },
        ),
    ]
