# Generated by Django 6.1.1 on 2026-09-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
        ('entrenamiento', '0002_etiquetaentidad_intencion_ejemplo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='intencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencion_detectada', to='entrenamiento.intencion'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='mensaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_detectado', to='chat.mensaje'),
        ),
        migrations.AddField(
            model_name='entidaddetectada',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='core.analisis'),
        ),
        migrations.AddField(
            model_name='entidaddetectada',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiquetas_detectadas', to='entrenamiento.etiquetaentidad'),
        ),
    ]
