# Generated by Django 6.1.1 on 2026-09-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_mensaje_conversacion_pedido'),
        ('core', '0002_initial'),
        ('entrenamiento', '0003_par_mensaje_respuesta_alter_ejemplo_conversacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='intencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencion_analisis', to='entrenamiento.intencion'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='mensaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_analisis', to='chat.mensaje'),
        ),
        migrations.AlterField(
            model_name='entidaddetectada',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_entidad', to='core.analisis'),
        ),
        migrations.AlterField(
            model_name='entidaddetectada',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiqueta_entidad', to='entrenamiento.etiquetaentidad'),
        ),
    ]
