# Generated by Django 6.1.1 on 2026-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_servicio_tiempo_aproximado'),
        ('entrenamiento', '0002_alter_par_mensaje_respuesta_mensaje_chatbot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='intenciones',
            field=models.ManyToManyField(blank=True, null=True, related_name='intenciones_conversaciones', to='entrenamiento.intencion'),
        ),
    ]
