# Generated by Django 6.1.1 on 2026-09-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversacion_tipo_conversacion_intenciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='intenciones',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tenemosCompra',
            field=models.BooleanField(default=False),
        ),
    ]
