"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# (configurar_entorno.py la genera y la escribe en .env; el fallback solo
#  evita que Django arranque con la clave vacia)
SECRET_KEY = os.getenv('SECRET_KEY') or 'django-insecure-cambia-esta-clave-en-CONFIGURAR'

# SECURITY WARNING: don't run with debug turned on in production!
# Ojo: getenv devuelve texto; "False" como texto seria cierto, hay que convertirlo
DEBUG = os.getenv('DEBUG', 'False').strip().lower() in ('1', 'true', 'yes')

# Hosts que puede servir: base de desarrollo/test + los declarados en .env
ALLOWED_HOSTS = list(dict.fromkeys(
    ['testserver', 'localhost', '127.0.0.1']
    + [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
))

# Origenes admitidos en peticiones cross-origin (widget embebido en otros sitios)
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'core',
    'chat',
    'notificaciones',
    'entrenamiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # En Docker, SQLITE_PATH=/data/db.sqlite3 apunta al volumen (persistencia)
        'NAME': os.getenv('SQLITE_PATH') or (BASE_DIR / 'db.sqlite3'),
    }
}

# Configuracion de spaCy
# Modelo base que vamos a usar
SPACY_MODEL_BASE = "es_core_news_sm"

# Cuando tengamos modelo propio, el path va aqui
SPACY_MODEL_PATH = BASE_DIR / "entrenamiento" / "spacy" / "modelo" / "model-best"

# Configuracion de la LLM
# Modelo base que vamos a usar
OLLAMA_HOST = os.getenv("OLLAMA_HOST")

# Variables del LLM
LLM_CONTEXT_SIZE = 2048
LLM_THREADS = 4
LLM_MAX_TOKENS = 200

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles" 


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/

# Backend: console para pruebas, smtp para producción
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Configuración del servidor SMTP
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'False').lower() in ('true', '1', 'yes')

# Lista segura de destinatarios (admite varios, no crashea si está vacío)
RESUMEN_EMAIL_DESTINATARIOS = [
    email.strip() for email in os.getenv('RESUMEN_EMAIL_DESTINATARIOS', '').split(',')
    if email.strip()
]
#Dominios que tienen permitido usar esa app
DOMINIOS_PERMITIDOS = [
    d.strip()
    for d in os.getenv('DOMINIOS_PERMITIDOS', 'http://localhost:8000').split(',')
    if d.strip()
]

#CONFIGURACIÓN JAZZMIN
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ChatBot",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "ChatBot",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "ChatBot",
    
    
    "welcome_sign": "Bienvenido al panel",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
        {"model": "auth.Group"},

    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ["auth"],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth"],

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "cursos": "fas fa-graduation-cap",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    # Elige un tema base (ej. 'default', 'flatly', 'cerulean')
    "theme": "lux", 
}

# Modelo del resumen (configurable desde .env; docker-compose lo baja en el setup)
OLLAMA_MODEL_RESUMEN = os.getenv('OLLAMA_MODEL_RESUMEN', 'llama3.2')

# Logging de la aplicacion
# - Consola: para desarrollo (runserver)
# - Archivo: logs/app.log con rotacion (10 MB x 10 backups)
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name} {module}:{lineno} - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "app.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
        "file_error": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / "error.log",
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 10,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": "ERROR",
        },
    },
    "loggers": {
        # Aplicacion (core, chat, entrenamiento, notificaciones)
        "core": {"handlers": ["console", "file", "file_error"], "level": "INFO", "propagate": False},
        "chat": {"handlers": ["console", "file", "file_error"], "level": "INFO", "propagate": False},
        "entrenamiento": {"handlers": ["console", "file", "file_error"], "level": "INFO", "propagate": False},
        "notificaciones": {"handlers": ["console", "file", "file_error"], "level": "INFO", "propagate": False},
        # Django
        "django": {"handlers": ["console", "file"], "level": "INFO", "propagate": False},
        "django.request": {"handlers": ["file", "file_error"], "level": "WARNING", "propagate": False},
        "django.db.backends": {"handlers": ["file"], "level": "WARNING", "propagate": False},
    },
}