# Generated by Django 6.1.1 on 2026-09-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('desripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Entidad',
                'verbose_name_plural': 'Etiquetas de Entidades',
            },
        ),
        migrations.CreateModel(
            name='Intencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Intencion',
                'verbose_name_plural': 'Intenciones',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_aproximado', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='EjemploNLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('chatbot', 'Chatbot')], default='chatbot', max_length=20)),
                ('mensaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_ejemploNLP', to='chat.mensaje')),
                ('intencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intencion_ejemploNLP', to='entrenamiento.intencion')),
            ],
            options={
                'verbose_name': 'Par de Entranamiento',
                'verbose_name_plural': 'Pares de Entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='Par_Mensaje_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_usuario', models.TextField(blank=True, null=True)),
                ('texto_chatbot', models.TextField(blank=True, null=True)),
                ('intencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intencion_par_mensaje_respuesta', to='entrenamiento.intencion')),
                ('mensaje_chatbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_chatbot_par_mensaje_resupuesta', to='chat.mensaje')),
                ('mensaje_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_usuario_par_mensaje_resupuesta', to='chat.mensaje')),
            ],
            options={
                'verbose_name': 'Par de Entranamiento',
                'verbose_name_plural': 'Pares de Entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='EjemploLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('chatbot', 'Chatbot')], default='chatbot', max_length=20)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamiento.par_mensaje_respuesta')),
            ],
            options={
                'verbose_name': 'Ejemplo',
                'verbose_name_plural': 'Ejemplos',
            },
        ),
        migrations.CreateModel(
            name='SpanEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.PositiveSmallIntegerField()),
                ('fin', models.PositiveSmallIntegerField()),
                ('ejemplo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplo_spansEntidad', to='entrenamiento.ejemplonlp')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etiqueta_spanEntidad', to='entrenamiento.etiquetaentidad')),
            ],
            options={
                'verbose_name': 'Entidad anotada',
                'verbose_name_plural': 'Entidades anotadas',
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='fin_mayor_que_inicio')],
            },
        ),
    ]
