# Generated by Django 6.1.1 on 2026-09-21 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplonlp',
            name='intencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intencion_ejemploNLP', to='entrenamiento.intencion'),
        ),
    ]
