# Generated by Django 6.1.1 on 2026-09-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('desripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Entidad',
                'verbose_name_plural': 'Etiquetas de Entidades',
            },
        ),
        migrations.CreateModel(
            name='Intencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Intencion',
                'verbose_name_plural': 'Intenciones',
            },
        ),
        migrations.CreateModel(
            name='Ejemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('chatbot', 'Chatbot')], default='chatbot', max_length=20)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.conversacion')),
            ],
            options={
                'verbose_name': 'Ejemplo',
                'verbose_name_plural': 'Ejemplos',
            },
        ),
    ]
