# Generated by Django 6.1.1 on 2026-09-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_servicio_tiempo_aproximado'),
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='mensaje_chatbot',
            field=models.OneToOneField(limit_choices_to={'remitente': 'chatbot'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_chatbot_par_mensaje_resupuesta', to='chat.mensaje'),
        ),
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='mensaje_usuario',
            field=models.OneToOneField(limit_choices_to={'remitente': 'usuario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_usuario_par_mensaje_resupuesta', to='chat.mensaje'),
        ),
    ]
