# Generated by Django 6.1.1 on 2026-09-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_mensaje_conversacion_pedido'),
        ('entrenamiento', '0002_etiquetaentidad_intencion_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Par_Mensaje_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_usuario', models.TextField()),
                ('texto_chatbot', models.TextField()),
                ('intencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intencion_par_mensaje_respuesta', to='entrenamiento.intencion')),
                ('mensaje_chatbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_chatbot_par_mensaje_resupuesta', to='chat.mensaje')),
                ('mensaje_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensaje_usuario_par_mensaje_resupuesta', to='chat.mensaje')),
            ],
            options={
                'verbose_name': 'Par de Entranamiento',
                'verbose_name_plural': 'Pares de Entrenamiento',
            },
        ),
        migrations.AlterField(
            model_name='ejemplo',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrenamiento.par_mensaje_respuesta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('intencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intencion_respuesta', to='entrenamiento.intencion')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
