# Generated by Django 6.1.1 on 2026-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_par_mensaje_respuesta_alter_ejemplo_conversacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='texto_chatbot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='texto_usuario',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
