# Generated by Django 6.1.1 on 2026-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_alter_par_mensaje_respuesta_texto_chatbot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='texto_chatbot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='par_mensaje_respuesta',
            name='texto_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
